urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns
from django.conf.urls import url

urlpatterns = patterns(
    'apps.merovingian.views',
    (r'^course/list/$', 'course.index'),
    (r'^course/list/(?P<faculty_id>\d+)$', 'course.index'),
    (r'^course/add/?$', 'course.add'),
    (r'^course/name/(?P<course_id>\d+)/$', 'course.name'),
    url(r'^course/(?P<course_id>\d+)/$', 'course.show', name='show'),
    (r'^course/(?P<course_id>\d+)/edit/$', 'course.edit'),
    (r'^course/(?P<course_id>\d+)/get_data/$', 'course.get_data'),

    (r'^course/specialty/(?P<sgroup_id>\d+)/module/list/$', 'module.list'),
    (r'^course/specialty/(?P<sgroup_id>\d+)/module/add/$', 'module.add'),
    (r'^course/specialty/(?P<sgroup_id>\d+)/module/(?P<module_id>\d+)/edit/$', 'module.edit'),
    (r'^course/specialty/(?P<sgroup_id>\d+)/module/(?P<module_id>\d+)/delete/$', 'module.delete'),
    
    (r'^course/studies_plan/(?P<sgroup_id>\d+)/$', 'sgroup.studies_plan'),
    (r'^course/studies_plan/(?P<sgroup_id>\d+)/syllabus/(?P<module_id>\d+)$', 'module.syllabuses'),
    
    (r'^course/profile/(?P<course_id>\d+)/$', 'profile.show'),
    (r'^course/profile/(?P<course_id>\d+)/edit/$', 'profile.edit'),
    
    (r'^course/diagnostic/(?P<course_id>\d+)/rules/$', 'diagnostic.edit'),
    
    (r'management/list/', 'management.index'),
    
    (r'^delete/confirm/$', 'delete_confirm'),
    (r'management/', 'management'),
    (r'', 'index'),
)

models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.validators import MinLengthValidator
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import ugettext_lazy as _
from django.utils.datetime_safe import datetime

from syjon import settings
from apps.syjon.lib.validators import validate_white_space
import math
import syjon
import datetime

def semesters_list():
    """
    Returns the list with numbers of all posible semesters.
    """
    return range(1,11)
semester_minimal = semesters_list()[0]
semester_maximal = semesters_list()[len(semesters_list())-1]

#########################################
#           MANAGERS
#########################################

def active_manager(klass):
    def active(self):
        return self.get_query_set().filter(is_active = True)
    klass.active = active
    return klass

def didactic_offer_manager(klass):
    def didactic_offer(self):
        return self.get_query_set().filter(didactic_offer__is_active = True, is_active = True)
    klass.didactic_offer = didactic_offer
    return klass

def didactic_offer_and_future_manager(klass):
    def didactic_offer_and_future(self):
        offer = DidacticOffer.objects.get(is_active=True)
        return self.get_query_set().filter(didactic_offer__start_date__gte = offer.start_date, is_active = True)
    klass.didactic_offer_and_future = didactic_offer_and_future
    return klass

def future_manager(klass):
    def future(self):
        offer = DidacticOffer.objects.get(is_active=True)
        return self.get_query_set().filter(didactic_offer__start_date__gt = offer.start_date, is_active = True)
    klass.future = future
    return klass
    
def latest_manager(klass):
    def latest(self):
        return self.get_query_set().filter(is_last = True, is_active = True)
    klass.latest = latest
    return klass


#########################################
#           ABSTRACTS
#########################################

class AbstractUniqueName(models.Model):
    class Meta:
        abstract = True
        ordering = ('name',)
        verbose_name = _(u'Name')
        verbose_name_plural = _(u'Names')

    name = models.CharField(max_length = 256,
                            unique = True,
                            verbose_name = _(u'name'),
                            validators = [MinLengthValidator(2), validate_white_space])

    def __unicode__(self):
        return unicode(self.name)

    def save(self, *args, **kwargs):
        self.name = self.name.strip()
        super(AbstractUniqueName, self).save(*args, **kwargs)

class AbstractName(models.Model):
    class Meta:
        abstract = True
        ordering = ('name',)
        verbose_name = _(u'Name')
        verbose_name_plural = _(u'Names')

    name = models.CharField(max_length = 256,
                            verbose_name = _(u'name'),
                            validators = [MinLengthValidator(2), validate_white_space])

    def __unicode__(self):
        return unicode(self.name)

    def save(self, *args, **kwargs):
        self.name = self.name.strip()
        super(AbstractName, self).save(*args, **kwargs)

class AbstractActive(AbstractName):
    class Meta:
        abstract = True
        ordering = ('-is_active', 'name')
        verbose_name = _(u'Name, active')
        verbose_name_plural = _(u'Names, active')
        
    is_active = models.BooleanField(default = True,
                                    verbose_name = _(u'Active'))

    def __unicode__(self):
        return '%s, %s' % (unicode(self.name), unicode(self.is_active))

    def set_active(self, active):
        self.is_active = active
        self.save()

class AbstractDidacticOffer(AbstractActive):
    class Meta:
        abstract = True
        ordering = ('-is_active', 'name')
        verbose_name = _(u'Teaching offer record')
        verbose_name_plural = _(u'Teaching offer records')

    didactic_offer = models.ForeignKey('DidacticOffer',
                                       db_column = 'id_didactic_offer',
                                       null = True,
                                       blank = True,
                                       verbose_name = _(u'Teaching offer'))

    def __unicode__(self):
        return unicode(self.name)

    def get_start_date(self):
        raise NotImplementedError

    def get_end_date(self):
        raise NotImplementedError

    def get_prev(self):
        raise NotImplementedError

    def get_next(self):
        raise NotImplementedError

    def is_course_first(self):
        raise NotImplementedError

    def is_course_last(self):
        raise NotImplementedError

    def _find_offer_for_date(self, offers, date):
        for offer in offers:
            if date >= offer.start_date and date <= offer.end_date:
                return offer
        return None

    def date(self, date, sem = 0, begin = True):
        """
        Returns the date of current didactic offer after sem semesters.
        It will be the beginning or endind date of current didactic offer but with replaced year.
        
        It is used to calculate ie. the start and end date of course. 
        """
        
        def find_active_offer(offers):
            for offer in offers:
                if offer.is_active:
                    return offer
            return None
        
        if not date:
            return None
        
        if sem < 0:
            sem = 0
        
        didactic_offers = DidacticOffer.objects.order_by('start_date')
        i = 0
        offers_cnt = len(didactic_offers)
        while i < offers_cnt:
            offer = didactic_offers[i]
            if date >= offer.start_date and date <= offer.end_date:
                break
            i += 1
        
        i += sem
        if i >= offers_cnt:
            return None
        
        offer = didactic_offers[i]
        if begin:
            return offer.start_date
        else:
            return offer.end_date

    def diff(self, date0, date1):
        """
        Return the number of semesters between dates date0 and date1.
        """
        offers = DidacticOffer.objects.order_by('start_date')

        offer0 = self._find_offer_for_date(offers, date0)
        offer1 = self._find_offer_for_date(offers, date1)
        
        if not offer0 or not offer1:
            return None
        
        if date0 < date1:
            start_offer = offer0
            end_offer = offer1
        else:
            start_offer = offer1
            end_offer = offer0
        
        semester = 0
        for offer in offers:
            if offer == end_offer:
                break
            elif offer == start_offer:
                semester = 1
            elif semester > 0:
                semester += 1
        return semester 

#########################################
#           SETTINGS
#########################################

class MerovingianSettings(models.Model):
    class Meta:
        db_table = 'merv_settings'
        verbose_name = _(u'Merowing Settings')
        verbose_name_plural = _(u'Merowing Settings')

    key = models.CharField(db_column = 'key',
                           max_length = 32,
                           unique = True,
                           verbose_name = _(u'key'))
    value = models.CharField(max_length = 128,
                             verbose_name = _(u'value'))

    def __unicode__(self):
        return '%s: %s' % (unicode(self.key), unicode(self.value))

class MerovingianAdmin(models.Model):
    class Meta:
        db_table = 'merv_admin'
        verbose_name = _(u'Merowing Administrator')
        verbose_name_plural = _(u'Merowing Administrator')

    user_profile = models.OneToOneField('trainman.UserProfile',
                                        db_column = 'merv_admin__to__user_profile',
                                        verbose_name = _(u'User'))
    
    temporary_privileged_access = models.BooleanField(default = False,
                                                      verbose_name = _(u'Temporary Privileged Access'))
    courses = models.ManyToManyField('Course',
                                    db_table = 'merv_admin__to__course',
                                    null = True,
                                    blank = True,
                                    verbose_name = _(u'Managed courses'))

    def __unicode__(self):
        return unicode(self.user_profile)

class MerovingianNews(AbstractActive):
    class Meta:
        db_table = 'merv_news'
        ordering = ('-date', '-is_active')
        verbose_name = _(u'News')
        verbose_name_plural = _(u'News')
    
    date = models.DateField(db_column = 'date',
                            verbose_name = _(u'date'))
    text = models.TextField(verbose_name = _(u'content'))

#########################################
#           DIDACTIC OFFER
#########################################

class DidacticOffer(AbstractActive):
    class Meta:
        db_table = 'merv_didactic_offer'
        verbose_name = _(u'Teaching offer')
        verbose_name_plural = _(u'Teaching offers')

    start_date = models.DateField(db_column = 'start_date',
                                  verbose_name = _(u'start date'))
    end_date = models.DateField(db_column = 'end_date',
                                verbose_name = _(u'end date'))

    def __unicode__(self):
        return '%s, %s, %s - %s' % (unicode(self.name), unicode(self.is_active), unicode(self.start_date), unicode(self.end_date))

    def save(self, *args, **kwargs):
        if self.is_active:
            for d in DidacticOffer.objects.filter(is_active = True):
                d.set_active(False)
        super(DidacticOffer, self).save(*args, **kwargs)


#########################################
#               COURSES
#########################################

LEVEL_BA = 8
LEVEL_MSC = 9
LEVEL_PHD = 10
LEVEL_U_MSC = 11
LEVEL_ENG = 12

templates/merovingian/didactic_offer/didactic_offer_form.html
{% extends "merovingian/didactic_offer/didactic_offers.html" %}

{% load i18n %}

{% block page_title %}
{{ block.super }}
| {{ didactic_offer }}
{% endblock %}

{% block breadcrumb %}
{{ block.super }}
{% if didactic_offer %}
&raquo; <a href="{% url apps.merovingian.views.didactic_offer_edit didactic_offer.id %}">{{ didactic_offer }}</a>
{% else %}
&raquo; <a href="{% url apps.merovingian.views.didactic_offer_show %}">{% trans "Teaching offers" %}</a>
{% endif %}
{% endblock %}

{% block content %}
<div id="didactic_offer_form">
{% if didactic_offer %}
<form action="{% url apps.merovingian.views.didactic_offer_edit didactic_offer.id %}" method="post">
{% else %}
<form action="{% url apps.merovingian.views.didactic_offer_add %}" method="post">
{% endif %}
  {% csrf_token %}
  
  <table class="table_0">
    <thead>
      <tr><td class="left" colspan="4">{% trans "Teaching offer attributes" %}</td></tr>
    </thead>
    <tbody>
      <tr>
	<td class="left label">{% trans "Name" %}:</td>
	<td>{{ didactic_offer_form.errors.name }} {{ didactic_offer_form.name }}</td>
      </tr>
      <tr>
	<td class="left label">{% trans "Start date" %}:</td>
	<td>{{ didactic_offer_form.errors.start_date }} {{ didactic_offer_form.start_date }}</td>
      </tr>
      <tr>
	<td class="left label">{% trans "End date" %}:</td>
	<td>{{ didactic_offer_form.errors.end_date }} {{ didactic_offer_form.end_date }}</td>
      </tr>
      <tr>
	<td class="left label">{% trans "Active" %}:</td>
	<td>{{ didactic_offer_form.errors.is_active }} {{ didactic_offer_form.is_active }}</td>
      </tr>
    </tbody>
  </table>
  
  <div class="spacer_10"></div>
  <div class="submit">
    <button class="button_2" type="submit" name="action" value="save_and_edit">
      {% trans "Save and stay on this page" %}
    </button>
    <button class="button_2" type="submit" name="action" value="save">
      {% trans "Save and return to the list" %}
    </button>
  </div>
</div>
</form>
{% endblock %}

templates/merovingian/didactic_offer/didactic_offers.html
{% extends "merovingian/base.html" %}

{% load i18n %}

{% block page_title %}
{{ block.super }}
{% endblock %}

{% block breadcrumb %}
{{ block.super }}
&raquo; <a href="{% url apps.merovingian.views.didactic_offer_show %}">{% trans "Teaching offers" %}</a>
{% endblock %}

{% block content %}
<div id="didactic_offers">

  {% load search %}
  {% search search_form request.path %}
  
  <div class="spacer_10"></div>
  
  {% if perms.merovingian.add_didacticoffer %}
  <a class="link_add link_0" href="{% url apps.merovingian.views.didactic_offer_add %}">{% trans "Add new teaching offer" %}</a>
  <div class="spacer_10"></div>
  {% endif %}
  
  <table class="table_0">
    <thead>
      <tr>
	<td class="left name">{% trans "Name" %}</td>
	<td class="left start_date">{% trans "Start date" %}</td>
	<td class="left end_date">{% trans "End date" %}</td>
	<td class="center is_active">{% trans "Active" %}</td>
      </tr>      
    </thead>
    <tbody>
      {% for didactic_offer in didactic_offer_page.object_list %}
      <tr class="{% cycle 'odd' 'even' %}">
	<td class="left"><a class="link_0" href="{% url apps.merovingian.views.didactic_offer_edit didactic_offer.id %}">{{ didactic_offer.name }}</a></td>
	<td class="left">{{ didactic_offer.start_date }}</td>
	<td class="left">{{ didactic_offer.end_date }}</td>
	<td class="center"><span class="{{ didactic_offer.is_active|yesno:"link_yes,link_no" }}"></span></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
  <div class="spacer_10"></div>

  {% load paginator %}
  {% paginator didactic_offer_page %}

</div>

{% endblock %}